name: Formatting and Unit tests

on: [push]

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run formatter 
        uses: docker://crnkofe/rust-base:latest
        with:
          args: cargo fmt -- --check

      - name: Run clippy
        uses: docker://crnkofe/rust-base:latest
        with:
          args: cargo clippy -- -Dwarnings 

      - name: Run unit tests
        uses: docker://crnkofe/rust-base:latest
        with:
          args: RUSTFLAGS='-L native=/usr/local/lib/libtermbox.a' cargo test
